# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Crypto Diary
#tagline:             'Documentation of crypto learnings'
#description:         'This blog is to document what I learn in cryptography'
url:                 http://esotericnomen.github.io/cryptdiary/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Rajkumar Ramasamy
  url:               http://esotericnomen.github.io/cryptdiary/
  email:             rraj.be@gmail.com

# Custom vars
version:             1.0.0
